PREFIX  xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  fx:   <http://sparql.xyz/facade-x/ns/>
PREFIX  ex: <http://example.org/>
PREFIX  xsd: <http://www.w3.org/2001/XMLSchema#>
CONSTRUCT
  {
    ?subject ex:p ?asserted_object1 .
    ?asserted_object2  ex:q << ?subject ex:p ?asserted_object1 >>.
    << ?asserted_object2  ex:q << ?subject ex:p ?asserted_object1 >> >> ex:r ?object .
  }
WHERE
  { SERVICE <x-sparql-anything:location=./data1.csv,csv.headers=true>
      { 

        []  xyz:c1-1 ?c1; 
            xyz:c1-2 ?c2;
            xyz:c1-3 ?c3;
            xyz:c1-4 ?c4 .

        bind(uri(concat(str(ex:),encode_for_uri(?c1))) as ?subject)
        bind(uri(concat(str(ex:),encode_for_uri(?c2))) as ?asserted_object1)
        bind(uri(concat(str(ex:),encode_for_uri(?c3))) as ?asserted_object2)
        
      }
    SERVICE <x-sparql-anything:location=./data2.csv,csv.headers=true>
      { 

        []  xyz:c2-1 ?c5; 
            xyz:c2-2 ?c4 .

        bind(uri(concat(str(ex:),encode_for_uri(?c5))) as ?object)        

      }
  }